spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wjx
    username: root
    password: cjh050217

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              MySQL8Dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true


  sql:
    init:
      platform: mysql
      separator: ;
      encoding: UTF-8
      mode: always
      schema-locations: classpath:schema.sql
#      data-locations: classpath:sql/data.sql

  thymeleaf:
    check-template-location: false


mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.wjx.mybatis.entity
server:
  port: 8080
  address: localhost



